name: "SPFx CICD"
description: "Build, bundle, package, test and deploys sppkg"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  CI-SPFx:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: SharePointSSOComponent

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Node.js runtime
      - name: Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      # Install npm
      - name: Run npm install
        shell: bash
        run: npm install

      # Build
      - name: Build
        shell: bash
        run: gulp build

      # Bundle and Package
      - name: Bundle and package
        shell: bash
        run: |
          gulp bundle --ship
          gulp package-solution --ship

      # Publish artifact
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sppkg-files
          path: "**/*.sppkg"
          if-no-files-found: error
